[package]
name = "dysql-macro"
version = "0.7.0"
edition = "2021"
description = "Dysql is a rust crate that do dynamic-sql query through proc-macro, it bases on tokio-postgres (default feature) and sqlx crate"
license = "Apache-2.0"

[features]
default = ["sqlx"]
tokio-postgres = []
sqlx = []

[lib]
proc-macro = true

[dependencies]
# dysql= "0.7"
dysql = { path = "../dysql" }
syn = { version="1.0", features=["extra-traits", "visit-mut"] }
proc-macro2 = { version="1.0", features = ["span-locations"] }
quote = { version="1.0" }
ramhorns = "0.14"
once_cell = "1.13"

[dev-dependencies]
tokio-postgres = { version = "0.7", features = ["with-chrono-0_4"] }
tokio = { version = "1.0", features = ["full"] }
tokio-pg-mapper = "0.2"
tokio-pg-mapper-derive = "0.2"
sqlx = { version = "0.6", features = [ "runtime-tokio-native-tls" , "postgres",  "mysql", "sqlite", "chrono", "uuid" ] }
