[package]
name = "dysql-macro"
version = "0.1.2"
edition = "2021"
description = "Dysql adds the ability of dynamic sql to tokio-postgres through proc macro. it uses Ramhorns the high performance template engine implementation of Mustache"
license = "Apache-2.0"

[lib]
proc-macro = true

[dependencies]
syn = {version="1.0", features=["extra-traits", "visit-mut"]}
proc-macro2 = {version="1.0", features = ["span-locations"]}
quote = {version="1.0"}
dysql= "0.1.1"
# dysql = { path = "../dysql" }
ramhorns = "0.14"
tokio-postgres = { version = "0.7", features = ["with-chrono-0_4"] }