[package]
name = "dysql-core"
version = "0.10.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
once_cell = "1.13"
rust-crypto = "0.2"
ramhorns-ext = { version = "0.17", features = ["chrono", "uuid"] }
serde = { version = "1.0", features = ["derive"] }