#![feature(prelude_import)]
#[prelude_import]
use std::prelude::rust_2021::*;
#[macro_use]
extern crate std;
use std::str::FromStr;
use dysql::{Content, SortModel, PageDto, page};
use sqlx::{
    FromRow, SqliteConnection, sqlite::{SqliteConnectOptions, SqliteJournalMode},
    ConnectOptions,
};
fn main() {
    let body = async {
        let mut conn = connect_sqlite_db().await;
        let dto = UserDto {
            id: None,
            name: None,
            age: Some(13),
            id_rng: None,
        };
        let sort_model = <[_]>::into_vec(
            #[rustc_box]
            ::alloc::boxed::Box::new([
                SortModel {
                    field: "id".to_owned(),
                    sort: "desc".to_owned(),
                },
            ]),
        );
        let mut pg_dto = PageDto::new_with_sort(3, 10, dto, sort_model);
        let rst = 'rst_block: {
            let sql_tpl = match dysql::get_sql_template(13984379367786963976u64) {
                Some(tpl) => tpl,
                None => {
                    let serd_template = [
                        9u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        58u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        83u8,
                        69u8,
                        76u8,
                        69u8,
                        67u8,
                        84u8,
                        32u8,
                        99u8,
                        111u8,
                        117u8,
                        110u8,
                        116u8,
                        40u8,
                        42u8,
                        41u8,
                        32u8,
                        70u8,
                        82u8,
                        79u8,
                        77u8,
                        32u8,
                        40u8,
                        115u8,
                        101u8,
                        108u8,
                        101u8,
                        99u8,
                        116u8,
                        32u8,
                        42u8,
                        32u8,
                        102u8,
                        114u8,
                        111u8,
                        109u8,
                        32u8,
                        116u8,
                        101u8,
                        115u8,
                        116u8,
                        95u8,
                        117u8,
                        115u8,
                        101u8,
                        114u8,
                        32u8,
                        119u8,
                        104u8,
                        101u8,
                        114u8,
                        101u8,
                        32u8,
                        49u8,
                        32u8,
                        61u8,
                        32u8,
                        49u8,
                        32u8,
                        4u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        100u8,
                        97u8,
                        116u8,
                        97u8,
                        206u8,
                        102u8,
                        120u8,
                        165u8,
                        87u8,
                        24u8,
                        125u8,
                        61u8,
                        2u8,
                        0u8,
                        0u8,
                        0u8,
                        3u8,
                        0u8,
                        0u8,
                        0u8,
                        1u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        32u8,
                        4u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        110u8,
                        97u8,
                        109u8,
                        101u8,
                        155u8,
                        174u8,
                        103u8,
                        242u8,
                        255u8,
                        172u8,
                        182u8,
                        175u8,
                        2u8,
                        0u8,
                        0u8,
                        0u8,
                        1u8,
                        0u8,
                        0u8,
                        0u8,
                        21u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        97u8,
                        110u8,
                        100u8,
                        32u8,
                        110u8,
                        97u8,
                        109u8,
                        101u8,
                        32u8,
                        61u8,
                        32u8,
                        58u8,
                        100u8,
                        97u8,
                        116u8,
                        97u8,
                        46u8,
                        110u8,
                        97u8,
                        109u8,
                        101u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        4u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        4u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        1u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        32u8,
                        4u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        100u8,
                        97u8,
                        116u8,
                        97u8,
                        206u8,
                        102u8,
                        120u8,
                        165u8,
                        87u8,
                        24u8,
                        125u8,
                        61u8,
                        2u8,
                        0u8,
                        0u8,
                        0u8,
                        3u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        3u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        97u8,
                        103u8,
                        101u8,
                        249u8,
                        39u8,
                        20u8,
                        224u8,
                        131u8,
                        169u8,
                        2u8,
                        227u8,
                        2u8,
                        0u8,
                        0u8,
                        0u8,
                        1u8,
                        0u8,
                        0u8,
                        0u8,
                        19u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        97u8,
                        110u8,
                        100u8,
                        32u8,
                        97u8,
                        103u8,
                        101u8,
                        32u8,
                        62u8,
                        32u8,
                        58u8,
                        100u8,
                        97u8,
                        116u8,
                        97u8,
                        46u8,
                        97u8,
                        103u8,
                        101u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        4u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        1u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        32u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        4u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        9u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        41u8,
                        32u8,
                        97u8,
                        115u8,
                        32u8,
                        95u8,
                        116u8,
                        109u8,
                        112u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        8u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        110u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        180u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        83u8,
                        69u8,
                        76u8,
                        69u8,
                        67u8,
                        84u8,
                        32u8,
                        99u8,
                        111u8,
                        117u8,
                        110u8,
                        116u8,
                        40u8,
                        42u8,
                        41u8,
                        32u8,
                        70u8,
                        82u8,
                        79u8,
                        77u8,
                        32u8,
                        40u8,
                        115u8,
                        101u8,
                        108u8,
                        101u8,
                        99u8,
                        116u8,
                        32u8,
                        42u8,
                        32u8,
                        102u8,
                        114u8,
                        111u8,
                        109u8,
                        32u8,
                        116u8,
                        101u8,
                        115u8,
                        116u8,
                        95u8,
                        117u8,
                        115u8,
                        101u8,
                        114u8,
                        32u8,
                        119u8,
                        104u8,
                        101u8,
                        114u8,
                        101u8,
                        32u8,
                        49u8,
                        32u8,
                        61u8,
                        32u8,
                        49u8,
                        32u8,
                        123u8,
                        123u8,
                        35u8,
                        100u8,
                        97u8,
                        116u8,
                        97u8,
                        125u8,
                        125u8,
                        32u8,
                        123u8,
                        123u8,
                        35u8,
                        110u8,
                        97u8,
                        109u8,
                        101u8,
                        125u8,
                        125u8,
                        97u8,
                        110u8,
                        100u8,
                        32u8,
                        110u8,
                        97u8,
                        109u8,
                        101u8,
                        32u8,
                        61u8,
                        32u8,
                        58u8,
                        100u8,
                        97u8,
                        116u8,
                        97u8,
                        46u8,
                        110u8,
                        97u8,
                        109u8,
                        101u8,
                        123u8,
                        123u8,
                        47u8,
                        110u8,
                        97u8,
                        109u8,
                        101u8,
                        125u8,
                        125u8,
                        123u8,
                        123u8,
                        47u8,
                        100u8,
                        97u8,
                        116u8,
                        97u8,
                        125u8,
                        125u8,
                        32u8,
                        123u8,
                        123u8,
                        35u8,
                        100u8,
                        97u8,
                        116u8,
                        97u8,
                        125u8,
                        125u8,
                        123u8,
                        123u8,
                        35u8,
                        97u8,
                        103u8,
                        101u8,
                        125u8,
                        125u8,
                        97u8,
                        110u8,
                        100u8,
                        32u8,
                        97u8,
                        103u8,
                        101u8,
                        32u8,
                        62u8,
                        32u8,
                        58u8,
                        100u8,
                        97u8,
                        116u8,
                        97u8,
                        46u8,
                        97u8,
                        103u8,
                        101u8,
                        123u8,
                        123u8,
                        47u8,
                        97u8,
                        103u8,
                        101u8,
                        125u8,
                        125u8,
                        32u8,
                        123u8,
                        123u8,
                        47u8,
                        100u8,
                        97u8,
                        116u8,
                        97u8,
                        125u8,
                        125u8,
                        41u8,
                        32u8,
                        97u8,
                        115u8,
                        32u8,
                        95u8,
                        116u8,
                        109u8,
                        112u8,
                    ];
                    dysql::put_sql_template(13984379367786963976u64, &serd_template)
                        .expect("Unexpected error when put_sql_template")
                }
            };
            let sql_rendered = sql_tpl.render(&mut pg_dto);
            let sql_rendered = dysql::SqlNodeLinkList::new(&sql_rendered)
                .trim()
                .to_string();
            let extract_rst = dysql::extract_params(
                &sql_rendered,
                dysql::SqlDialect::from("sqlite".to_owned()),
            );
            if let Err(e) = extract_rst {
                break 'rst_block Err(
                    dysql::DySqlError(
                        dysql::ErrorInner::new(
                            dysql::Kind::ExtractSqlParamterError,
                            Some(Box::new(e)),
                            None,
                        ),
                    ),
                );
            }
            let (sql, param_names) = extract_rst.unwrap();
            let mut query = sqlx::query_scalar::<_, i64>(&sql);
            for i in 0..param_names.len() {
                if param_names[i] == "data.name" {
                    query = query.bind(&pg_dto.data.name);
                }
                if param_names[i] == "data.age" {
                    query = query.bind(&pg_dto.data.age);
                }
            }
            let rst = query.fetch_one(&mut conn).await;
            if let Err(e) = rst {
                break 'rst_block Err(
                    dysql::DySqlError(
                        dysql::ErrorInner::new(
                            dysql::Kind::QueryError,
                            Some(Box::new(e)),
                            None,
                        ),
                    ),
                );
            }
            let count = rst.expect("Unexpected error");
            {
                let _tmp_pg_dto: &mut PageDto<_> = &mut pg_dto;
                _tmp_pg_dto.init(count as u64);
            }
            let sql_tpl = match dysql::get_sql_template(15010016983795882405u64) {
                Some(tpl) => tpl,
                None => {
                    let serd_template = [
                        17u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        36u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        115u8,
                        101u8,
                        108u8,
                        101u8,
                        99u8,
                        116u8,
                        32u8,
                        42u8,
                        32u8,
                        102u8,
                        114u8,
                        111u8,
                        109u8,
                        32u8,
                        116u8,
                        101u8,
                        115u8,
                        116u8,
                        95u8,
                        117u8,
                        115u8,
                        101u8,
                        114u8,
                        32u8,
                        119u8,
                        104u8,
                        101u8,
                        114u8,
                        101u8,
                        32u8,
                        49u8,
                        32u8,
                        61u8,
                        32u8,
                        49u8,
                        32u8,
                        4u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        100u8,
                        97u8,
                        116u8,
                        97u8,
                        206u8,
                        102u8,
                        120u8,
                        165u8,
                        87u8,
                        24u8,
                        125u8,
                        61u8,
                        2u8,
                        0u8,
                        0u8,
                        0u8,
                        3u8,
                        0u8,
                        0u8,
                        0u8,
                        1u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        32u8,
                        4u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        110u8,
                        97u8,
                        109u8,
                        101u8,
                        155u8,
                        174u8,
                        103u8,
                        242u8,
                        255u8,
                        172u8,
                        182u8,
                        175u8,
                        2u8,
                        0u8,
                        0u8,
                        0u8,
                        1u8,
                        0u8,
                        0u8,
                        0u8,
                        21u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        97u8,
                        110u8,
                        100u8,
                        32u8,
                        110u8,
                        97u8,
                        109u8,
                        101u8,
                        32u8,
                        61u8,
                        32u8,
                        58u8,
                        100u8,
                        97u8,
                        116u8,
                        97u8,
                        46u8,
                        110u8,
                        97u8,
                        109u8,
                        101u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        4u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        4u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        1u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        32u8,
                        4u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        100u8,
                        97u8,
                        116u8,
                        97u8,
                        206u8,
                        102u8,
                        120u8,
                        165u8,
                        87u8,
                        24u8,
                        125u8,
                        61u8,
                        2u8,
                        0u8,
                        0u8,
                        0u8,
                        3u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        3u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        97u8,
                        103u8,
                        101u8,
                        249u8,
                        39u8,
                        20u8,
                        224u8,
                        131u8,
                        169u8,
                        2u8,
                        227u8,
                        2u8,
                        0u8,
                        0u8,
                        0u8,
                        1u8,
                        0u8,
                        0u8,
                        0u8,
                        19u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        97u8,
                        110u8,
                        100u8,
                        32u8,
                        97u8,
                        103u8,
                        101u8,
                        32u8,
                        62u8,
                        32u8,
                        58u8,
                        100u8,
                        97u8,
                        116u8,
                        97u8,
                        46u8,
                        97u8,
                        103u8,
                        101u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        4u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        1u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        32u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        4u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        1u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        32u8,
                        7u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        105u8,
                        115u8,
                        95u8,
                        115u8,
                        111u8,
                        114u8,
                        116u8,
                        99u8,
                        159u8,
                        10u8,
                        70u8,
                        155u8,
                        166u8,
                        22u8,
                        114u8,
                        2u8,
                        0u8,
                        0u8,
                        0u8,
                        5u8,
                        0u8,
                        0u8,
                        0u8,
                        10u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        32u8,
                        79u8,
                        82u8,
                        68u8,
                        69u8,
                        82u8,
                        32u8,
                        66u8,
                        89u8,
                        32u8,
                        10u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        115u8,
                        111u8,
                        114u8,
                        116u8,
                        95u8,
                        109u8,
                        111u8,
                        100u8,
                        101u8,
                        108u8,
                        200u8,
                        246u8,
                        183u8,
                        221u8,
                        11u8,
                        176u8,
                        170u8,
                        162u8,
                        2u8,
                        0u8,
                        0u8,
                        0u8,
                        3u8,
                        0u8,
                        0u8,
                        0u8,
                        1u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        32u8,
                        5u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        102u8,
                        105u8,
                        101u8,
                        108u8,
                        100u8,
                        40u8,
                        172u8,
                        131u8,
                        36u8,
                        109u8,
                        221u8,
                        13u8,
                        73u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        1u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        32u8,
                        4u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        115u8,
                        111u8,
                        114u8,
                        116u8,
                        106u8,
                        136u8,
                        129u8,
                        166u8,
                        96u8,
                        207u8,
                        134u8,
                        127u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        2u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        44u8,
                        32u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        4u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        13u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        32u8,
                        33u8,
                        91u8,
                        66u8,
                        95u8,
                        68u8,
                        69u8,
                        76u8,
                        40u8,
                        44u8,
                        41u8,
                        93u8,
                        32u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        4u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        7u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        32u8,
                        76u8,
                        73u8,
                        77u8,
                        73u8,
                        84u8,
                        32u8,
                        9u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        112u8,
                        97u8,
                        103u8,
                        101u8,
                        95u8,
                        115u8,
                        105u8,
                        122u8,
                        101u8,
                        175u8,
                        198u8,
                        0u8,
                        107u8,
                        73u8,
                        61u8,
                        253u8,
                        139u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        8u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        32u8,
                        79u8,
                        70u8,
                        70u8,
                        83u8,
                        69u8,
                        84u8,
                        32u8,
                        5u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        115u8,
                        116u8,
                        97u8,
                        114u8,
                        116u8,
                        160u8,
                        91u8,
                        55u8,
                        101u8,
                        109u8,
                        155u8,
                        46u8,
                        182u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        8u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        122u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        30u8,
                        1u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        0u8,
                        115u8,
                        101u8,
                        108u8,
                        101u8,
                        99u8,
                        116u8,
                        32u8,
                        42u8,
                        32u8,
                        102u8,
                        114u8,
                        111u8,
                        109u8,
                        32u8,
                        116u8,
                        101u8,
                        115u8,
                        116u8,
                        95u8,
                        117u8,
                        115u8,
                        101u8,
                        114u8,
                        32u8,
                        119u8,
                        104u8,
                        101u8,
                        114u8,
                        101u8,
                        32u8,
                        49u8,
                        32u8,
                        61u8,
                        32u8,
                        49u8,
                        32u8,
                        123u8,
                        123u8,
                        35u8,
                        100u8,
                        97u8,
                        116u8,
                        97u8,
                        125u8,
                        125u8,
                        32u8,
                        123u8,
                        123u8,
                        35u8,
                        110u8,
                        97u8,
                        109u8,
                        101u8,
                        125u8,
                        125u8,
                        97u8,
                        110u8,
                        100u8,
                        32u8,
                        110u8,
                        97u8,
                        109u8,
                        101u8,
                        32u8,
                        61u8,
                        32u8,
                        58u8,
                        100u8,
                        97u8,
                        116u8,
                        97u8,
                        46u8,
                        110u8,
                        97u8,
                        109u8,
                        101u8,
                        123u8,
                        123u8,
                        47u8,
                        110u8,
                        97u8,
                        109u8,
                        101u8,
                        125u8,
                        125u8,
                        123u8,
                        123u8,
                        47u8,
                        100u8,
                        97u8,
                        116u8,
                        97u8,
                        125u8,
                        125u8,
                        32u8,
                        123u8,
                        123u8,
                        35u8,
                        100u8,
                        97u8,
                        116u8,
                        97u8,
                        125u8,
                        125u8,
                        123u8,
                        123u8,
                        35u8,
                        97u8,
                        103u8,
                        101u8,
                        125u8,
                        125u8,
                        97u8,
                        110u8,
                        100u8,
                        32u8,
                        97u8,
                        103u8,
                        101u8,
                        32u8,
                        62u8,
                        32u8,
                        58u8,
                        100u8,
                        97u8,
                        116u8,
                        97u8,
                        46u8,
                        97u8,
                        103u8,
                        101u8,
                        123u8,
                        123u8,
                        47u8,
                        97u8,
                        103u8,
                        101u8,
                        125u8,
                        125u8,
                        32u8,
                        123u8,
                        123u8,
                        47u8,
                        100u8,
                        97u8,
                        116u8,
                        97u8,
                        125u8,
                        125u8,
                        32u8,
                        123u8,
                        123u8,
                        35u8,
                        105u8,
                        115u8,
                        95u8,
                        115u8,
                        111u8,
                        114u8,
                        116u8,
                        125u8,
                        125u8,
                        32u8,
                        79u8,
                        82u8,
                        68u8,
                        69u8,
                        82u8,
                        32u8,
                        66u8,
                        89u8,
                        32u8,
                        123u8,
                        123u8,
                        35u8,
                        115u8,
                        111u8,
                        114u8,
                        116u8,
                        95u8,
                        109u8,
                        111u8,
                        100u8,
                        101u8,
                        108u8,
                        125u8,
                        125u8,
                        32u8,
                        123u8,
                        123u8,
                        102u8,
                        105u8,
                        101u8,
                        108u8,
                        100u8,
                        125u8,
                        125u8,
                        32u8,
                        123u8,
                        123u8,
                        115u8,
                        111u8,
                        114u8,
                        116u8,
                        125u8,
                        125u8,
                        44u8,
                        32u8,
                        123u8,
                        123u8,
                        47u8,
                        115u8,
                        111u8,
                        114u8,
                        116u8,
                        95u8,
                        109u8,
                        111u8,
                        100u8,
                        101u8,
                        108u8,
                        125u8,
                        125u8,
                        32u8,
                        33u8,
                        91u8,
                        66u8,
                        95u8,
                        68u8,
                        69u8,
                        76u8,
                        40u8,
                        44u8,
                        41u8,
                        93u8,
                        32u8,
                        123u8,
                        123u8,
                        47u8,
                        105u8,
                        115u8,
                        95u8,
                        115u8,
                        111u8,
                        114u8,
                        116u8,
                        125u8,
                        125u8,
                        32u8,
                        76u8,
                        73u8,
                        77u8,
                        73u8,
                        84u8,
                        32u8,
                        123u8,
                        123u8,
                        112u8,
                        97u8,
                        103u8,
                        101u8,
                        95u8,
                        115u8,
                        105u8,
                        122u8,
                        101u8,
                        125u8,
                        125u8,
                        32u8,
                        79u8,
                        70u8,
                        70u8,
                        83u8,
                        69u8,
                        84u8,
                        32u8,
                        123u8,
                        123u8,
                        115u8,
                        116u8,
                        97u8,
                        114u8,
                        116u8,
                        125u8,
                        125u8,
                        32u8,
                    ];
                    dysql::put_sql_template(15010016983795882405u64, &serd_template)
                        .expect("Unexpected error when put_sql_template")
                }
            };
            let sql_rendered = sql_tpl.render(&mut pg_dto);
            let sql_rendered = dysql::SqlNodeLinkList::new(&sql_rendered)
                .trim()
                .to_string();
            let extract_rst = dysql::extract_params(
                &sql_rendered,
                dysql::SqlDialect::from("sqlite".to_owned()),
            );
            if let Err(e) = extract_rst {
                break 'rst_block Err(
                    dysql::DySqlError(
                        dysql::ErrorInner::new(
                            dysql::Kind::ExtractSqlParamterError,
                            Some(Box::new(e)),
                            None,
                        ),
                    ),
                );
            }
            let (sql, param_names) = extract_rst.unwrap();
            let mut query = sqlx::query_as::<_, User>(&sql);
            for i in 0..param_names.len() {
                if param_names[i] == "data.name" {
                    query = query.bind(&pg_dto.data.name);
                }
                if param_names[i] == "data.age" {
                    query = query.bind(&pg_dto.data.age);
                }
            }
            let rst = query.fetch_all(&mut conn).await;
            if let Err(e) = rst {
                break 'rst_block Err(
                    dysql::DySqlError(
                        dysql::ErrorInner::new(
                            dysql::Kind::QueryError,
                            Some(Box::new(e)),
                            None,
                        ),
                    ),
                );
            }
            let rst = rst.expect("Unexpected error");
            let pg_data = dysql::Pagination::from_dto(&pg_dto, rst);
            Ok(pg_data)
        }
            .unwrap();
    };
    #[allow(clippy::expect_used, clippy::diverging_sub_expression)]
    {
        return tokio::runtime::Builder::new_multi_thread()
            .enable_all()
            .build()
            .expect("Failed building the Runtime")
            .block_on(body);
    }
}
async fn connect_sqlite_db() -> SqliteConnection {
    let mut conn = SqliteConnectOptions::from_str("sqlite::memory:")
        .unwrap()
        .journal_mode(SqliteJournalMode::Wal)
        .read_only(false)
        .connect()
        .await
        .unwrap();
    sqlx::query("DROP TABLE IF EXISTS test_user").execute(&mut conn).await.unwrap();
    sqlx::query(
            r#"
        CREATE TABLE test_user (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            name VARCHAR(255) NULL,
            age INT NULL
        )"#,
        )
        .execute(&mut conn)
        .await
        .unwrap();
    conn
}
struct UserDto {
    id: Option<i64>,
    name: Option<String>,
    age: Option<i32>,
    id_rng: Option<Vec<i32>>,
}
impl ::dysql::Content for UserDto {
    #[inline]
    fn capacity_hint(&self, tpl: &::dysql::Template) -> usize {
        tpl.capacity_hint() + self.id.capacity_hint(tpl) + self.id_rng.capacity_hint(tpl)
            + self.name.capacity_hint(tpl) + self.age.capacity_hint(tpl)
    }
    #[inline]
    fn render_section<C, E, IC>(
        &self,
        section: ::dysql::Section<C>,
        encoder: &mut E,
        _content: Option<&IC>,
    ) -> std::result::Result<(), E::Error>
    where
        C: ::dysql::traits::ContentSequence,
        E: ::dysql::encoding::Encoder,
    {
        section.with(self).render(encoder, Option::<&()>::None)
    }
    #[inline]
    fn render_notnone_section<C, E, IC>(
        &self,
        section: ::dysql::Section<C>,
        encoder: &mut E,
        _content: Option<&IC>,
    ) -> std::result::Result<(), E::Error>
    where
        C: ::dysql::traits::ContentSequence,
        E: ::dysql::encoding::Encoder,
    {
        section.with(self).render(encoder, Option::<&()>::None)
    }
    #[inline]
    fn render_field_escaped<E>(
        &self,
        hash: u64,
        name: &str,
        encoder: &mut E,
    ) -> std::result::Result<bool, E::Error>
    where
        E: ::dysql::encoding::Encoder,
    {
        match hash {
            3133790766199404813u64 => self.id.render_escaped(encoder).map(|_| true),
            12620297671082892063u64 => self.id_rng.render_escaped(encoder).map(|_| true),
            12661497617682247323u64 => self.name.render_escaped(encoder).map(|_| true),
            16357823180428290041u64 => self.age.render_escaped(encoder).map(|_| true),
            _ => Ok(false),
        }
    }
    #[inline]
    fn render_field_unescaped<E>(
        &self,
        hash: u64,
        name: &str,
        encoder: &mut E,
    ) -> std::result::Result<bool, E::Error>
    where
        E: ::dysql::encoding::Encoder,
    {
        match hash {
            3133790766199404813u64 => self.id.render_unescaped(encoder).map(|_| true),
            12620297671082892063u64 => {
                self.id_rng.render_unescaped(encoder).map(|_| true)
            }
            12661497617682247323u64 => self.name.render_unescaped(encoder).map(|_| true),
            16357823180428290041u64 => self.age.render_unescaped(encoder).map(|_| true),
            _ => Ok(false),
        }
    }
    fn render_field_section<P, E>(
        &self,
        hash: u64,
        name: &str,
        section: ::dysql::Section<P>,
        encoder: &mut E,
    ) -> std::result::Result<bool, E::Error>
    where
        P: ::dysql::traits::ContentSequence,
        E: ::dysql::encoding::Encoder,
    {
        match hash {
            3133790766199404813u64 => {
                self.id
                    .render_section(section, encoder, Option::<&()>::None)
                    .map(|_| true)
            }
            12620297671082892063u64 => {
                self.id_rng
                    .render_section(section, encoder, Option::<&()>::None)
                    .map(|_| true)
            }
            12661497617682247323u64 => {
                self.name
                    .render_section(section, encoder, Option::<&()>::None)
                    .map(|_| true)
            }
            16357823180428290041u64 => {
                self.age
                    .render_section(section, encoder, Option::<&()>::None)
                    .map(|_| true)
            }
            _ => Ok(false),
        }
    }
    fn render_field_inverse<P, E>(
        &self,
        hash: u64,
        name: &str,
        section: ::dysql::Section<P>,
        encoder: &mut E,
    ) -> std::result::Result<bool, E::Error>
    where
        P: ::dysql::traits::ContentSequence,
        E: ::dysql::encoding::Encoder,
    {
        match hash {
            3133790766199404813u64 => {
                self.id
                    .render_inverse(section, encoder, Option::<&()>::None)
                    .map(|_| true)
            }
            12620297671082892063u64 => {
                self.id_rng
                    .render_inverse(section, encoder, Option::<&()>::None)
                    .map(|_| true)
            }
            12661497617682247323u64 => {
                self.name
                    .render_inverse(section, encoder, Option::<&()>::None)
                    .map(|_| true)
            }
            16357823180428290041u64 => {
                self.age
                    .render_inverse(section, encoder, Option::<&()>::None)
                    .map(|_| true)
            }
            _ => Ok(false),
        }
    }
    fn render_field_notnone_section<P, E>(
        &self,
        hash: u64,
        name: &str,
        section: ::dysql::Section<P>,
        encoder: &mut E,
    ) -> std::result::Result<bool, E::Error>
    where
        P: ::dysql::traits::ContentSequence,
        E: ::dysql::encoding::Encoder,
    {
        match hash {
            3133790766199404813u64 => {
                self.id.render_notnone_section(section, encoder, Option::<&()>::None)?;
                Ok(self.id.is_truthy())
            }
            12620297671082892063u64 => {
                self.id_rng
                    .render_notnone_section(section, encoder, Option::<&()>::None)?;
                Ok(self.id_rng.is_truthy())
            }
            12661497617682247323u64 => {
                self.name.render_notnone_section(section, encoder, Option::<&()>::None)?;
                Ok(self.name.is_truthy())
            }
            16357823180428290041u64 => {
                self.age.render_notnone_section(section, encoder, Option::<&()>::None)?;
                Ok(self.age.is_truthy())
            }
            _ => Ok(false),
        }
    }
}
struct User {
    id: i64,
    name: Option<String>,
    age: Option<i32>,
}
#[automatically_derived]
impl<'a, R: ::sqlx::Row> ::sqlx::FromRow<'a, R> for User
where
    &'a ::std::primitive::str: ::sqlx::ColumnIndex<R>,
    i64: ::sqlx::decode::Decode<'a, R::Database>,
    i64: ::sqlx::types::Type<R::Database>,
    Option<String>: ::sqlx::decode::Decode<'a, R::Database>,
    Option<String>: ::sqlx::types::Type<R::Database>,
    Option<i32>: ::sqlx::decode::Decode<'a, R::Database>,
    Option<i32>: ::sqlx::types::Type<R::Database>,
{
    fn from_row(row: &'a R) -> ::sqlx::Result<Self> {
        let id: i64 = row.try_get("id")?;
        let name: Option<String> = row.try_get("name")?;
        let age: Option<i32> = row.try_get("age")?;
        ::std::result::Result::Ok(User { id, name, age })
    }
}
#[automatically_derived]
impl ::core::fmt::Debug for User {
    fn fmt(&self, f: &mut ::core::fmt::Formatter) -> ::core::fmt::Result {
        ::core::fmt::Formatter::debug_struct_field3_finish(
            f,
            "User",
            "id",
            &self.id,
            "name",
            &self.name,
            "age",
            &&self.age,
        )
    }
}
#[automatically_derived]
impl ::core::marker::StructuralPartialEq for User {}
#[automatically_derived]
impl ::core::cmp::PartialEq for User {
    #[inline]
    fn eq(&self, other: &User) -> bool {
        self.id == other.id && self.name == other.name && self.age == other.age
    }
}
