[package]
name = "dysql-project"
version = "0.4.1"
edition = "2021"
description = "Dysql is a rust crate that do dynamic-sql query through proc-macro, it bases on tokio-postgres and sqlx crate (default feature)"
license = "Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dysql-macro = { path = "./dysql-macro" }
dysql = { path = "./dysql" }