[package]
name = "workspace"
version = "0.0.0"
edition = "2021"
build = "./build.rs"

[workspace]
members = [
    "dysql-tpl",
    "dysql-tpl-derive",
    "dysql-core",
    "dysql-macro",
    "dysql",
]

[patch.crates-io]
# dysql = { path = "./dysql" }
# dysql-tpl = { path = "./dysql-tpl" }
# dysql-tpl-derive = { path = "./dysql-tpl-derive" }
# dysql-core = { path = "./dysql-core" }
# dysql-macro = { path = "./dysql-macro" }

[profile.bench]
lto = "fat"
codegen-units = 1


[dev-dependencies]
# test_sql dependence
dysql = { path = "./dysql" }
dotenv = "0.15"
tokio = { version = "1.0", features = ["full"] }
sqlx = { version = "0.7", features = [ "runtime-tokio-native-tls" , "postgres",  "mysql", "sqlite", "chrono", "uuid" ] }

# test_tpl dependence
askama = "0.12"
handlebars = "4.4"
serde = "1.0"
serde_derive = "1.0"
mustache = "0.9"
tera = "1.2.0"
ahash = "0.8"

[package.metadata.scripts]
test_sqlx = "cargo clean -p dysql-core && cargo test"