[package]
name = "dysql-project"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dysql-macro = {path = "./dysql-macro"}
dysql = {path = "./dysql"}