version: "3.1"
services:
  postgres:
    image: postgres:11
    restart: always
    environment:
      POSTGRES_PASSWORD: 111111
      POSTGRES_USER: root
      POSTGRES_DB: my_database
    ports:
      - 5432:5432
    deploy:
      resources:
        limits:
          memory: '512M'
          cpus: '1'
    volumes:
      - db:/var/lib/postgresql/data
  mysql:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 111111
      MYSQL_DATABASE: my_database
    ports:
      - 3306:3306
    volumes:
      - db:/var/lib/mysql/data
volumes:
    db: