[package]
name = "seaorm"
version = "0.1.0"
edition = "2021"

[workspace]

[dependencies]
tokio = { version = "1.20", features = ["macros", "rt-multi-thread"] }
sea-orm = { version = "0.12", features = ["sqlx-postgres", "sqlx-sqlite", "runtime-tokio-rustls", "macros"]}