[package]
name = "dysql"
version = "0.8.8"
edition = "2021"
description = "Dysql is a rust crate that do dynamic-sql query through proc-macro, it bases on tokio-postgres (default feature) and sqlx crate"
license = "Apache-2.0"

[dependencies]
rust-crypto = "0.2"
once_cell = "1.13"
ramhorns = "0.14"
serde = { version = "1.0", features = ["derive"] }