[package]
name = "dysql"
version = "0.10.0"
edition = "2021"
description = "Dysql is a rust crate that do dynamic-sql query through proc-macro, it bases on sqlx crate"
license = "Apache-2.0"
repository = "https://github.com/evanzp0/dysql-project"
documentation = "https://docs.rs/dysql"
readme = "../README.md"

[lib]
name = "dysql"

[dependencies]
dysql-core = "0.10"
dysql-macro = "0.10"
once_cell = "1.13"
ramhorns-ext = { version = "0.17", features = ["chrono", "uuid"] }
serde = { version = "1.0", features = ["derive"] }